#cloud-config

coreos:
  units:
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        BindIPv6Only=both
        Service=docker.service

        [Install]
        WantedBy=sockets.target
    - name: "docker-mysql.service"
      command: "start"
      content: |
        [Unit]
        Description=Mysql container
        Author=Robin
        After=docker.service

        [Service]
        Restart=always
        ExecStart=/usr/bin/docker run --name mysql --net host -v /opt/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD mysql:5.7
        ExecStop=/usr/bin/docker rm -f mysql
